---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    zscaler_pem_destination: /tmp

  tasks:
    - name: "Include mtik00.zscaler"
      ansible.builtin.include_role:
        name: "mtik00.zscaler"
